# Generated by Django 4.2.17 on 2024-12-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_data_user'),
    ]

    operations = [
    ]
